version: "3"

services:

  web:
    build:
      context: services/web
    volumes:
      - ./src:/var/www/app
    depends_on:
      - database
    ports:
      - "${HTTP_PORT}:80"
    env_file:
      - ./.env
    environment:
      APP_NAME: "${COMPOSE_PROJECT_NAME}"
      APP_URL: "${APP_URL}"
      DB_CONNECTION: mysql
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: "${MYSQL_DATABASE}"
      DB_USERNAME: "${MYSQL_USER}"
      DB_PASSWORD: "${MYSQL_PASSWORD}"

  php-cli:
    build:
      context: services/php-cli
      args:
        USER_ID: "${USER_ID}"
        GROUP_ID: "${GROUP_ID}"
    volumes:
      - ./src:/var/www/app
    depends_on:
      - database
    env_file:
      - ./.env
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
      APP_NAME: "${COMPOSE_PROJECT_NAME}"
      APP_URL: "${APP_URL}"
      DB_CONNECTION: mysql
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: "${MYSQL_DATABASE}"
      DB_USERNAME: "${MYSQL_USER}"
      DB_PASSWORD: "${MYSQL_PASSWORD}"

  node:
    build:
      context: ./services/node
      args:
        USER_ID: "${USER_ID}"
        GROUP_ID: "${GROUP_ID}"
    volumes:
      - ./src:/var/www/app
    env_file:
      - ./.env

  database:
    build:
      context: ./services/database
    volumes:
      - database:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    env_file:
      - ./.env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 0

volumes:
  database:
